# BACKUP
- hosts: "{{plone_servers|default('all')}}"
  roles: [corpusops.roles/ansible_plugins]
  tasks:
  - when: ["cops_plone_lifecycle_prebackup|default(true)"]
    tags: ["cops_plone_lifecycle_prebackup"]
    block:
    - include_role: {name: plone_vars, allow_duplicates: false, public: true}
    become: true
  - block:
    - stat: {path: "{{cops_plone_dir}}"}
      register: has_project_directory
    - set_fact:
        cops_project_backup_postgresql: "{{cops_plone_backup_postgresql}}"
        app_is_available: "{{has_project_directory.stat.exists}}"
    - include_role: {name: "corpusops.roles/project_backup", public: false}
      when: "app_is_available"
    become: true
    vars:
      cops_project_backup_postgresql: "{{cops_plone_backup_postgresql}}"
      cops_project_backup_paths_to_backup: "{{cops_plone_backup_paths_to_backup}}"
      cops_project_backup_docker_volumes: "{{cops_plone_backup_docker_volumes_}}"
      cops_project_backup_pgdump_urls: "{{cops_plone_backup_pgdump_urls}}"
      cops_project_backup_dir: "{{cops_project_backups_dir}}/{{cops_plone_db_name}}"
